name: Test

on:
  push:
    branches: [ main ]
    paths:
      - 'gruyere/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'gruyere/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
            python-version: "3.13"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y lsof

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run pytest -v