name: Type Check

on:
  push:
    branches: [ main ]
    paths:
      - 'gruyere-py/**/*.py'
      - 'gruyere-py/pyproject.toml'
      - '.github/workflows/typecheck.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'gruyere-py/**/*.py'
      - 'gruyere-py/pyproject.toml'
      - '.github/workflows/typecheck.yml'

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync
        working-directory: gruyere-py

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
